/**
 * `core.di` — Hilt dependency-injection modules.
 *
 * Hosts the application-scoped `@Module` definitions that contribute bindings to
 * the graph generated by `@HiltAndroidApp`. The modules here start as placeholders
 * (no providers yet) and are filled by later tasks:
 *  - [com.teleautomation.android.core.di.NetworkModule] — OkHttp, Retrofit,
 *    interceptors, cookie jar, and the `NetworkResult` classifier wiring.
 *  - [com.teleautomation.android.core.di.StorageModule] — DataStore and
 *    `EncryptedSharedPreferences`-backed session/identity storage.
 */
package com.teleautomation.android.core.di
